%将数据转存到矩阵
%x1
figx1(:,1)=x1.time;
figx1(:,2)=x1.signals(1).values;
figx1(:,3)=x1.signals(2).values;
%x2
figx2(:,1)=x2.time;
figx2(:,2)=x2.signals(1).values;
figx2(:,3)=x2.signals(2).values;
%x3
figx3(:,1)=x3.time;
figx3(:,2)=x3.signals(1).values;
figx3(:,3)=x3.signals(2).values;
%u1
figu1(:,1)=u1.time;
figu1(:,2)=u1.signals.values;
%u2
figu2(:,1)=u2.time;
figu2(:,2)=u2.signals.values;
%ve
figve(:,1)=ve.time;
figve(:,2)=ve.signals(1).values;
figve(:,3)=ve.signals(2).values;
figve(:,4)=ve.signals(3).values;
%thetae
figthetae(:,1)=thetae.time;
figthetae(:,2)=thetae.signals(1).values;
figthetae(:,3)=thetae.signals(2).values;
figthetae(:,4)=thetae.signals(3).values;
